### ISSUE TITLE
Repo name cleanup

### ISSUE THREAD

**Issue by jsirish** [dynamic/foxystripe#176]
Since we're close to publishing this to Packagist, I want to make sure we clean up the repo names before we do.

Nic - what's a good naming scheme for FoxyStripe and all the related add-ons? Camel case or lower case? Things like that.

I do like prefixing all add-ons with FoxyStripe - FoxyStripe Members, for example.

Thoughts?

**Comment by muskie9** [comment]
I guess part of the question could be, do we want to have the namespace be FoxyStripe and move the module and supporting addons in there... so FoxyStripe/SilverStripe FoxyStripe rather than dynamic/FoxyStripe. It would break existing instances, but assuming people would want to use the new stable release they'd do rigorous testing to make sure any other breakages are fixed.

**Comment by rywa** [comment]
Just my 2 cents:

Repos

dynamic/foxystripe
dynamic/foxystripe-module-name
dynamic/foxystripe-other-module-name

Packagist

dynamic/foxystripe

Namespacing

Start with

Dynamic

And if you want, sub namespace to 

Dynamic\FoxyStripe

**Comment by jsirish** [comment]
Nic - interesting idea with the foxystripe namespace. But I think we should keep it dynamic, so our other non-foxystripe modules are in the same namespace.

I think Ryan's correct, both with the scheme and the capitalization patterns. 

* dynamic/foxystripe
* dynamic/foxystripe-members
* dynamic/foxystripe-integrations

I'd like to go ahead and make these changes. Since we've got a couple of projects using the module, we'll need to update our submodule references. But better now than after people start using it right?

**Comment by muskie9** [comment]
I dig.
